# 01 — Explore SVoD Dataset

This notebook loads and explores the Streaming dataset (Netflix, Hulu, Prime Video, Disney+).

In [1]:
import pandas as pd
import matplotlib.pyplot as plt
from pathlib import Path

In [2]:
DATA_DIR = Path.cwd().parents[0] / "Data"  # adjust if needed

def load_csv(filename: str) -> pd.DataFrame:
    fp = DATA_DIR / filename

    if fp.exists():
        print(f"Loaded: {fp}")
        return pd.read_csv(fp)
    raise FileNotFoundError(
        f"Could not find {filename} in any of: {[str(d) for d in DATA_DIR]}"
    )

In [3]:
df_movie = load_csv("MoviesOnStreamingPlatforms.csv")
df_tv = load_csv("TVShowsOnStreamingPlatforms.csv")

print("df_movie_shape:", df_movie.shape)
print("df_tv shape:", df_tv.shape)

Loaded: /home/csantosh/Build_Projects/streaming-bi-template/Data/MoviesOnStreamingPlatforms.csv
Loaded: /home/csantosh/Build_Projects/streaming-bi-template/Data/TVShowsOnStreamingPlatforms.csv
df_movie_shape: (9515, 15)
df_tv shape: (5368, 15)

In [5]:
df_movie.head()

,ID,Title,Year,Age,Rotten Tomatoes,Netflix,Hulu,Prime Video,Disney+,Type,Genre,Country,Language,IMDb,IMDb_ID
0,1,The Irishman,2019,18+,98/100,1,0,0,0,0,"Biography, Crime, Drama",United States,"English, Italian, Latin, Spanish, German",7.8,tt1302006
1,2,Dangal,2016,7+,97/100,1,0,0,0,0,"Action, Biography, Drama","India, United States","Hindi, English",8.3,tt5074352
2,3,David Attenborough: A Life on Our Planet,2020,7+,95/100,1,0,0,0,0,"Documentary, Biography",United Kingdom,English,8.9,tt11989890
3,4,Lagaan: Once Upon a Time in India,2001,7+,94/100,1,0,0,0,0,"Drama, Musical, Sport","India, United States","Hindi, English",8.1,tt0169102
4,5,Roma,2018,18+,94/100,1,0,0,0,0,Drama,"Mexico, United States","Spanish, Mixtec, English, Japanese, German, Fr...",7.6,tt6155172

In [6]:
# Example: df = pd.read_csv(DATA_DIR / "svod_sample.csv")
print("Place your dataset (e.g., svod_sample.csv) in the data/ folder.")

Place your dataset (e.g., svod_sample.csv) in the data/ folder.

### Explore movie data

In [7]:
df_movie.head()

,ID,Title,Year,Age,Rotten Tomatoes,Netflix,Hulu,Prime Video,Disney+,Type,Genre,Country,Language,IMDb,IMDb_ID
0,1,The Irishman,2019,18+,98/100,1,0,0,0,0,"Biography, Crime, Drama",United States,"English, Italian, Latin, Spanish, German",7.8,tt1302006
1,2,Dangal,2016,7+,97/100,1,0,0,0,0,"Action, Biography, Drama","India, United States","Hindi, English",8.3,tt5074352
2,3,David Attenborough: A Life on Our Planet,2020,7+,95/100,1,0,0,0,0,"Documentary, Biography",United Kingdom,English,8.9,tt11989890
3,4,Lagaan: Once Upon a Time in India,2001,7+,94/100,1,0,0,0,0,"Drama, Musical, Sport","India, United States","Hindi, English",8.1,tt0169102
4,5,Roma,2018,18+,94/100,1,0,0,0,0,Drama,"Mexico, United States","Spanish, Mixtec, English, Japanese, German, Fr...",7.6,tt6155172

In [8]:
df_movie.info()

<class 'pandas.DataFrame'>
RangeIndex: 9515 entries, 0 to 9514
Data columns (total 15 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   ID               9515 non-null   int64
 1   Title            9515 non-null   str
 2   Year             9515 non-null   int64
 3   Age              5338 non-null   str
 4   Rotten Tomatoes  9508 non-null   str
 5   Netflix          9515 non-null   int64
 6   Hulu             9515 non-null   int64
 7   Prime Video      9515 non-null   int64
 8   Disney+          9515 non-null   int64
 9   Type             9515 non-null   int64
 10  Genre            6030 non-null   str
 11  Country          6387 non-null   str
 12  Language         6026 non-null   str
 13  IMDb             6732 non-null   float64
 14  IMDb_ID          6787 non-null   str
dtypes: float64(1), int64(7), str(7)
memory usage: 1.1 MB

In [9]:
df_movie.describe()

,ID,Year,Netflix,Hulu,Prime Video,Disney+,Type,IMDb
count,9515.000000,9515.000000,9515.000000,9515.000000,9515.000000,9515.000000,9515.0,6732.000000
mean,4758.000000,2007.422386,0.388334,0.110037,0.432265,0.096900,0.0,6.604947
std,2746.888239,19.130367,0.487397,0.312952,0.495417,0.295837,0.0,2.148151
min,1.000000,1914.000000,0.000000,0.000000,0.000000,0.000000,0.0,1.000000
25%,2379.500000,2006.000000,0.000000,0.000000,0.000000,0.000000,0.0,5.800000
50%,4758.000000,2015.000000,0.000000,0.000000,0.000000,0.000000,0.0,7.000000
75%,7136.500000,2018.000000,1.000000,0.000000,1.000000,0.000000,0.0,8.000000
max,9515.000000,2021.000000,1.000000,1.000000,1.000000,1.000000,0.0,10.000000

### Explore TV shows

In [10]:
df_tv.head()

,ID,Title,Year,Age,Rotten Tomatoes,Netflix,Hulu,Prime Video,Disney+,Type,Genre,Country,Language,IMDb,IMDb_ID
0,1,Breaking Bad,2008,18+,100/100,1,0,0,0,1,"crime television series, drama television seri...",United States,"American English, Spanish language in the Amer...",10.0,tt0903747
1,2,Stranger Things,2016,16+,96/100,1,0,0,0,1,"science fiction television program, horror tel...",United States,English,9.0,tt4574334
2,3,Attack on Titan,2013,18+,95/100,1,1,0,0,1,NaN,NaN,NaN,9.0/10,NaN
3,4,Better Call Saul,2015,18+,94/100,1,0,0,0,1,"legal drama, crime television series",United States,English,10.0,tt3032476
4,5,Dark,2017,16+,93/100,1,0,0,0,1,"science fiction television program, drama tele...",Germany,German,10.0,tt5753856

In [11]:
df_tv.info()

<class 'pandas.DataFrame'>
RangeIndex: 5368 entries, 0 to 5367
Data columns (total 15 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   ID               5368 non-null   int64
 1   Title            5368 non-null   str
 2   Year             5368 non-null   int64
 3   Age              3241 non-null   str
 4   Rotten Tomatoes  5368 non-null   str
 5   Netflix          5368 non-null   int64
 6   Hulu             5368 non-null   int64
 7   Prime Video      5368 non-null   int64
 8   Disney+          5368 non-null   int64
 9   Type             5368 non-null   int64
 10  Genre            2210 non-null   str
 11  Country          2697 non-null   str
 12  Language         2043 non-null   str
 13  IMDb             4498 non-null   str
 14  IMDb_ID          2688 non-null   str
dtypes: int64(7), str(8)
memory usage: 629.2 KB

In [15]:
df_tv.describe()

,ID,Year,Netflix,Hulu,Prime Video,Disney+,Type
count,5368.000000,5368.000000,5368.000000,5368.000000,5368.000000,5368.000000,5368.0
mean,2814.945790,2012.628726,0.367176,0.301975,0.341095,0.065387,1.0
std,1672.385727,10.142813,0.482080,0.459157,0.474122,0.247231,0.0
min,1.000000,1904.000000,0.000000,0.000000,0.000000,0.000000,1.0
25%,1345.750000,2011.000000,0.000000,0.000000,0.000000,0.000000,1.0
50%,2788.000000,2016.000000,0.000000,0.000000,0.000000,0.000000,1.0
75%,4308.250000,2018.000000,1.000000,1.000000,1.000000,0.000000,1.0
max,5717.000000,2021.000000,1.000000,1.000000,1.000000,1.000000,1.0

In [16]:
if 'watch_time' in df_movie.columns:
    df_movie['watch_time'].hist()
    plt.title('Watch Time Distribution')
    plt.show()

In [ ]:
# Example EDA once data is loaded
# df.head()
# df.info()
# df.describe(numeric_only=True)

## Quick Plot Example

In [ ]:
# if 'watch_time' in df.columns:
#     df['watch_time'].hist()
#     plt.title('Watch Time Distribution')
#     plt.show()